item-colors:
    air:
    stone:
    grass:
    dirt:
    cobblestone:
    wood:
    sapling:
    bedrock:
    water:
    stationary_water:
    lava:
    stationary_lava:
    sand:
    gravel:
    gold_ore:
    iron_ore:
    coal_ore:
    log:
    leaves:
    sponge:
    glass:
    lapis_ore:
    lapis_block:
    dispenser:
    sandstone:
    note_block:
    bed_block:
    powered_rail:
    detector_rail:
    piston_sticky_base:
    web:
    long_grass:
    dead_bush:
    piston_base:
    piston_extension:
    wool:
    piston_moving_piece:
    yellow_flower:
    red_rose:
    brown_mushroom:
    red_mushroom:
    gold_block:
    iron_block:
    double_step:
    step:
    brick:
    tnt:
    bookshelf:
    mossy_cobblestone:
    obsidian:
    torch:
    fire:
    mob_spawner:
    wood_stairs:
    chest:
    redstone_wire:
    diamond_ore:
    diamond_block:
    workbench:
    crops:
    soil:
    furnace:
    burning_furnace:
    sign_post:
    wooden_door:
    ladder:
    rails:
    cobblestone_stairs:
    wall_sign:
    lever:
    stone_plate:
    iron_door_block:
    wood_plate:
    redstone_ore:
    glowing_redstone_ore:
    redstone_torch_off:
    redstone_torch_on:
    stone_button:
    snow:
    ice:
    snow_block:
    cactus:
    clay:
    sugar_cane_block:
    jukebox:
    fence:
    pumpkin:
    netherrack:
    soul_sand:
    glowstone:
    portal:
    jack_o_lantern:
    cake_block:
    diode_block_off:
    diode_block_on:
    locked_chest:
    stained_glass:
    trap_door:
    monster_eggs:
    smooth_brick:
    huge_mushroom_1:
    huge_mushroom_2:
    iron_fence:
    thin_glass:
    melon_block:
    pumpkin_stem:
    melon_stem:
    vine:
    fence_gate:
    brick_stairs:
    smooth_stairs:
    mycel:
    water_lily:
    nether_brick:
    nether_fence:
    nether_brick_stairs:
    nether_warts:
    enchantment_table:
    brewing_stand:
    cauldron:
    ender_portal:
    ender_portal_frame:
    ender_stone:
    dragon_egg:
    redstone_lamp_off:
    redstone_lamp_on:
    wood_double_step:
    wood_step:
    cocoa:
    sandstone_stairs:
    emerald_ore:
    ender_chest:
    tripwire_hook:
    tripwire:
    emerald_block:
    spruce_wood_stairs:
    birch_wood_stairs:
    jungle_wood_stairs:
    command:
    beacon:
    cobble_wall:
    flower_pot:
    carrot:
    potato:
    wood_button:
    skull:
    anvil:
    trapped_chest:
    gold_plate:
    iron_plate:
    redstone_comparator_off:
    redstone_comparator_on:
    daylight_detector:
    redstone_block:
    quartz_ore:
    hopper:
    quartz_block:
    quartz_stairs:
    activator_rail:
    dropper:
    stained_clay:
    stained_glass_pane:
    leaves_2:
    log_2:
    acacia_stairs:
    dark_oak_stairs:
    hay_block:
    carpet:
    hard_clay:
    coal_block:
    packed_ice:
    double_plant:
    iron_spade:
    iron_pickaxe:
    iron_axe:
    flint_and_steel:
    apple:
    bow:
    arrow:
    coal:
    diamond:
    iron_ingot:
    gold_ingot:
    iron_sword:
    wood_sword:
    wood_spade:
    wood_pickaxe:
    wood_axe:
    stone_sword:
    stone_spade:
    stone_pickaxe:
    stone_axe:
    diamond_sword:
    diamond_spade:
    diamond_pickaxe:
    diamond_axe:
    stick:
    bowl:
    mushroom_soup:
    gold_sword:
    gold_spade:
    gold_pickaxe:
    gold_axe:
    string:
    feather:
    sulphur:
    wood_hoe:
    stone_hoe:
    iron_hoe:
    diamond_hoe:
    gold_hoe:
    seeds:
    wheat:
    bread:
    leather_helmet:
    leather_chestplate:
    leather_leggings:
    leather_boots:
    chainmail_helmet:
    chainmail_chestplate:
    chainmail_leggings:
    chainmail_boots:
    iron_helmet:
    iron_chestplate:
    iron_leggings:
    iron_boots:
    diamond_helmet:
    diamond_chestplate:
    diamond_leggings:
    diamond_boots:
    gold_helmet:
    gold_chestplate:
    gold_leggings:
    gold_boots:
    flint:
    pork:
    grilled_pork:
    painting:
    golden_apple:
    sign:
    wood_door:
    bucket:
    water_bucket:
    lava_bucket:
    minecart:
    saddle:
    iron_door:
    redstone:
    snow_ball:
    boat:
    leather:
    milk_bucket:
    clay_brick:
    clay_ball:
    sugar_cane:
    paper:
    book:
    slime_ball:
    storage_minecart:
    powered_minecart:
    egg:
    compass:
    fishing_rod:
    watch:
    glowstone_dust:
    raw_fish:
    cooked_fish:
    ink_sack:
    bone:
    sugar:
    cake:
    bed:
    diode:
    cookie:
    map:
    shears:
    melon:
    pumpkin_seeds:
    melon_seeds:
    raw_beef:
    cooked_beef:
    raw_chicken:
    cooked_chicken:
    rotten_flesh:
    ender_pearl:
    blaze_rod:
    ghast_tear:
    gold_nugget:
    nether_stalk:
    potion:
    glass_bottle:
    spider_eye:
    fermented_spider_eye:
    blaze_powder:
    magma_cream:
    brewing_stand_item:
    cauldron_item:
    eye_of_ender:
    speckled_melon:
    monster_egg:
    exp_bottle:
    fireball:
    book_and_quill:
    written_book:
    emerald:
    item_frame:
    flower_pot_item:
    carrot_item:
    potato_item:
    baked_potato:
    poisonous_potato:
    empty_map:
    golden_carrot:
    skull_item:
    carrot_stick:
    nether_star:
    pumpkin_pie:
    firework:
    firework_charge:
    enchanted_book:
    redstone_comparator:
    nether_brick_item:
    quartz:
    explosive_minecart:
    hopper_minecart:
    iron_barding:
    gold_barding:
    diamond_barding:
    leash:
    name_tag:
    command_minecart:
    gold_record:
    green_record:
    record_3:
    record_4:
    record_5:
    record_6:
    record_7:
    record_8:
    record_9:
    record_10:
    record_11:
    record_12:
