name: ${pom.name}
main: ${pom.groupId}.${pom.name}
version: ${pom.version}
author: bendem
description: Send items to chat so others know what you speak about.

commands:
    itc:
        usage: |
            Usage:
            /<command> reload Reload config from file
            /<command> show <player> Shows an item to a player trough the chat
            /<command> send <player> Sends an item to a player trough the chat
            /<command> give <player> Gives an item to a player trough the chat
        description: ItemToChat commands
        permission: itemtochat.commands

permissions:
    itemtochat.*:
        description: Give access to all ItemToChat features
        children:
            itemtochat.commands: true
            itemtochat.chat: true
    itemtochat.commands.*:
        description: Give access to all ItemToChat commands
        children:
            itemtochat.commands.reload: true
            itemtochat.commands.show: true
            itemtochat.commands.send: true
            itemtochat.commands.give: true
            itemtochat.commands.transaction: true

    itemtochat.commands.reload:
        description: Reload config from file
        default: op
    itemtochat.commands.show:
        description: Use /itc show command
        default: true
    itemtochat.commands.send:
        description: Use /itc send command
        default: true
    itemtochat.commands.give:
        description: Use /itc give command
        default: op
    itemtochat.commands.transaction:
        description: Use /itc transaction command
        default: op

    itemtochat.chat.*:
        description: Give access to the chat related features
        children:
            itemtochat.chat.message: true
            itemtochat.chat.click: true

    itemtochat.chat.message:
        description: Show an item into the chat using a placeholder
        default: true
    itemtochat.chat.click:
        description: Click to get item on usable messages
        default: true

